### ISSUE TITLE
pretrained model?

### ISSUE THREAD

**Issue by seon92** [nayeemrizve/invariance-equivariance#3]
Hello! Thank you for sharing codes.

I've tried to reproduce the paper accuracies on miniImageNet, but failed. 
Could you share the pretrained models? or give some tips?

I used hyper-parameters in README. 

Best, 
Seon.

**Comment by nayeemrizve** [comment]
Please see https://github.com/nayeemrizve/invariance-equivariance/issues/4.

I would suggest using a smaller batch size for these two datasets. something like 32. For my experiments, I used 52/56 for GPU memory constraints.
